
name: deploy

on:
  push:
    branches:
      - react

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Build web-app
        run: | 
          npm ci
          npm run build
          git config --global user.name J-ma-rcos
          git config --global user.email "joaosantoslucas2013@hotmail.com"
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
